### ISSUE TITLE
pic16 modules (specifically multi_sensor) reset repeatedly, requiring executive reflash

### ISSUE THREAD

**Issue by amcgee** [WellDone/MoMo-Firmware#76] opened 2014-05-07 15:09 UTC
Keegan and I have both observed this.  It can be easily reproduced by adding a bus_master_rpc_sync call in app_task.  Unclear exactly why this happens, needs investigating.

**Comment by timburke** [comment] 2014-05-07 20:55
Hmm.  One difference between pic16lf1847 and the other modules is the 
use of paged flash.  This means that you cannot simply use the call 
instruction  to call a function but must use the fcall macro to also set 
the high bits of the address since the call instruction can only encode 
11 bits of the address.

It could be that calling bus_master_rpc_sync is not setting the high 
address bits, meaning the call is being redirected to random memory.  
One thing to check is if the assembly output for the call outputs the 
fcall macro of the call mnemonic.  If call is used and not preceeded by 
an movlp instruction this would be a fatal problem.  You can fix this by 
either using fcall or setting the page to zero manually with movlp 0 
immediately before a regular call instruction.

**Comment by amcgee** [comment] 2014-05-08 12:25
After further debugging it happens sporadically when 16-bit integers are
used.  It may also be related to code size, since using 16-bit integers
sometimes works but can then break when adding one more instruction that
uses them.

On Wed, May 7, 2014 at 11:55 PM, timburke notifications@github.com wrote:

> Hmm. One difference between pic16lf1847 and the other modules is the
> use of paged flash. This means that you cannot simply use the call
> instruction to call a function but must use the fcall macro to also set
> the high bits of the address since the call instruction can only encode
> 11 bits of the address.
> 
> It could be that calling bus_master_rpc_sync is not setting the high
> address bits, meaning the call is being redirected to random memory.
> One thing to check is if the assembly output for the call outputs the
> fcall macro of the call mnemonic. If call is used and not preceeded by
> an movlp instruction this would be a fatal problem. You can fix this by
> either using fcall or setting the page to zero manually with movlp 0
> immediately before a regular call instruction.
> 
> On 5/7/14, 5:09 PM, Austin McGee wrote:
> 
> > Keegan and I have both observed this. It can be easily reproduced by
> > adding a bus_master_rpc_sync call in app_task. Unclear exactly why
> > this happens, needs investigating.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/WellDone/MoMo-Firmware/issues/76.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/WellDone/MoMo-Firmware/issues/76#issuecomment-42481945
> .

## 

Austin McGee
austinwm@gmail.com
(510) 200-8486

**Comment by amcgee** [comment] 2014-05-21 20:18
(Tim's analysis) This is most likely an issue with program ROM size on 8-bit pics - a special longjump instruction sequence is required when the program size grows beyond 2kb.

**Comment by timburke** [comment] 2014-05-23 04:59
Have not yet been able to reproduce.  Working on more robust executive to this type of error, see #83.  Will also fix this bug when I can find it.

**Comment by timburke** [comment] 2014-07-01 03:10
This bug was caused by not waiting long enough in modtool for more than 4K of flash to be sent and programmed, leading to the upper half of memory being empty.  This is fixed in the current dev branch.

**Closed as completed by timburke** 2014-07-01 03:10 UTC
